name: AI Review Response

on:
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  process_review:
    if: |
      github.event.pull_request.head.ref != 'ai-unified-*' &&
      (contains(github.event.comment.body, '@ai-assistant') || github.event.review.state == 'changes_requested')
    concurrency:
      group: ai-pr-modification-${{ github.event.pull_request.number }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - uses: ./.github/actions/setup-deps
        with:
          python-version: '3.12'
      - name: Run review processor
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REVIEW_ID: ${{ github.event.review.id }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: python scripts/review_processor.py
