name: Auto Collect

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'   # 6 時間おき

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/_shared-deps.yml
        with:
          python-version: '3.11'

      - name: Cache pip wheels
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-


      # ------- Run collector & export run_dir -------
      - name: Run collector
        id: collect
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ST_CACHE:       ${{ github.workspace }}/.cache/st
          PYTHONPATH:     ${{ github.workspace }}
        run: |
          set -e
          python facade/collector.py \
                 --auto -n 50 \
                 --q-provider openai \
                 --ai-provider openai \
                 --quiet --summary

          # 直近の runs ディレクトリを取得して GITHUB_OUTPUT に渡す
          run_dir=$(ls -td runs/* | head -n 1 || true)
          echo "run_dir=$run_dir" >> "$GITHUB_OUTPUT"

      # ------- Upload result artefact --------------
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: por_history
          path: ${{ steps.collect.outputs.run_dir }}/por_history.csv
          retention-days: 30
