name: auto prune zero deltae

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install PyGithub pandas pyarrow
      - run: python scripts/prune_and_pr.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
