name: Build Dataset Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        artefact_name: [nightly-dataset, por-dataset]
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-deps
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            pip-${{ runner.os }}-
      - name: Cache HF models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: hf-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            hf-${{ runner.os }}-
      - name: Download raw CSV
        id: download_raw
        run: |
          set -euo pipefail
          if [ -z "$RAW_DATA_URL" ]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          mkdir -p raw
          curl -fsSL "$RAW_DATA_URL" | tar -xz -C raw
          test -f raw/*.csv
        env:
          RAW_DATA_URL: ${{ secrets.RAW_DATA_URL }}
      - name: Build dataset
        if: steps.download_raw.outputs.skip != 'true'
        id: build
        run: |
          CSV_PATH=datasets/current.csv
          python scripts/build_dataset.py --out-csv "$CSV_PATH" \
                                         --out-parquet datasets/current.parquet
      - name: Recalculate metrics
        if: steps.download_raw.outputs.skip != 'true'
        run: |
          python scripts/recalc_scores_v4.py \
            --infile ${{ steps.build.outputs.csv }} \
            --outfile datasets/current_recalc.parquet
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artefact_name }}
          path: datasets/current_recalc.parquet
          if-no-files-found: skip
      - name: Create PR if changed
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Nightly dataset update"
          title: "Automated dataset update"
          branch: "dataset/nightly"
          delete-branch: true
