name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      #––– Cache pip wheels –––#
      - name: Cache pip wheels
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: >
            pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      #––– Cache HuggingFace models –––#
      - name: Cache HuggingFace models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: >
            hf-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            hf-${{ runner.os }}-
      - run: pip install -v -r requirements.txt types-openai
      - name: Sanity-check deps
        run: |
          test -f requirements.txt || { echo "❌ requirements.txt not found"; exit 1; }
          python - <<'PY'
          import importlib, sys
          for pkg in ("matplotlib", "pytest"):
              try:
                  m = importlib.import_module(pkg)
                  print(f"[OK] {pkg} {m.__version__}")
              except ModuleNotFoundError:
                  print(f"❌  {pkg} NOT INSTALLED")
                  sys.exit(1)
          PY
      - run: python -c "import matplotlib"
      - name: Static type check (mypy)
        run: mypy .
      - run: pytest -q
