name: secret-smoke
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      ST_CACHE: ${{ github.workspace }}/.cache/st
    steps:
      - name: Check secret
        run: echo "KEY=${{ secrets.OPENAI_API_KEY }}"
